// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPu8HAbpc-OU0J9SrWDXW3kh1ujYY1o40',
    appId: '1:715060977886:web:1ab8cdfc3f88d134a9224f',
    messagingSenderId: '715060977886',
    projectId: 'blood-donor-308b0',
    authDomain: 'blood-donor-308b0.firebaseapp.com',
    storageBucket: 'blood-donor-308b0.appspot.com',
    measurementId: 'G-V0BBDPZ1PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwgquJ-Riz92GjnrTmF1cWNLjSFLpaWkk',
    appId: '1:715060977886:android:aaabf3b1c189cfe6a9224f',
    messagingSenderId: '715060977886',
    projectId: 'blood-donor-308b0',
    storageBucket: 'blood-donor-308b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY6_5ePwxlw6d2KnlcEHHGaXXyc_sXjmg',
    appId: '1:715060977886:ios:aae1c304013a15ffa9224f',
    messagingSenderId: '715060977886',
    projectId: 'blood-donor-308b0',
    storageBucket: 'blood-donor-308b0.appspot.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY6_5ePwxlw6d2KnlcEHHGaXXyc_sXjmg',
    appId: '1:715060977886:ios:545f2c8375e19ae8a9224f',
    messagingSenderId: '715060977886',
    projectId: 'blood-donor-308b0',
    storageBucket: 'blood-donor-308b0.appspot.com',
    iosBundleId: 'com.example.bloodDonation.RunnerTests',
  );
}
